// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_1300_meters_over = "CgkInu3nveoEEAIQBA"; // <GPGSID>
        public const string achievement_11000_meters_over = "CgkInu3nveoEEAIQCQ"; // <GPGSID>
        public const string achievement_500_meters_over = "CgkInu3nveoEEAIQAg"; // <GPGSID>
        public const string achievement_800_meters_over = "CgkInu3nveoEEAIQAw"; // <GPGSID>
        public const string achievement_200_meters_over = "CgkInu3nveoEEAIQAA"; // <GPGSID>
        public const string leaderboard_maximum_depth = "CgkInu3nveoEEAIQAQ"; // <GPGSID>
        public const string achievement_2000_meters_over = "CgkInu3nveoEEAIQBQ"; // <GPGSID>
        public const string achievement_7800_meters_over = "CgkInu3nveoEEAIQCA"; // <GPGSID>
        public const string achievement_6200_meters_over = "CgkInu3nveoEEAIQBw"; // <GPGSID>
        public const string achievement_3600_meters_over = "CgkInu3nveoEEAIQBg"; // <GPGSID>

}

